version: '3'
services:
  redis:
    image: redis
    networks:
      - webnet
  slack:
    image: postgres
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: saizszmufvlzuvw0
      POSTGRES_USER: avnadmin
      POSTGRES_DB: slack
  web:
    image: slack-server

    networks:
      - webnet
    environment:
      REDIS_HOST: redis
      DB_HOST: slack
    depends_on:
      - slack
      - redis
    command: ['./wait-for-it.sh', 'slack:5432', '--', 'node', 'index.js']
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.template:/etc/nginx/conf.d/nginx.template
    ports:
      - '8080:80'
    networks:
      - webnet
    depends_on:
      - web
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
networks:
  webnet:
